# Generated by Django 2.1.2 on 2018-11-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0008_auto_20181126_1034'),
        ('carton', '0008_auto_20181126_0419'),
    ]

    operations = [
    ]
