# Generated by Django 2.1.2 on 2018-11-26 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carton', '0009_merge_20181126_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_past',
            field=models.ManyToManyField(to='carton.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions_current',
            field=models.ManyToManyField(to='carton.Session'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
